name: Build and Deploy .NET Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove existing output directory
        run: rm -rf ./output  # Remove the output directory if it exists

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  # Specify the .NET version you are using

      - name: Restore .NET dependencies
        run: dotnet restore ./eShopOnWeb.sln  # Adjust the path to your solution file

      - name: Build .NET solution
        run: dotnet build ./eShopOnWeb.sln --configuration Release  # Adjust the path as needed

      - name: Publish .NET application
        run: dotnet publish ./eShopOnWeb.sln --configuration Release --output ./output  # Consider unique output paths if necessary

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: midwebapp  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Ensure this secret is set in your repository
          package: './output'  # Path to the published output
