name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'  # Use the version your project targets

      - name: Restore dependencies
        run: dotnet restore ./eShopOnWeb.sln  # Ensure this path is correct

      - name: Build
        run: dotnet build ./eShopOnWeb.sln --configuration Release  # Ensure this path is correct

      - name: Publish
        run: dotnet publish ./eShopOnWeb.sln --configuration Release --output ./output  # Ensure this path is correct

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: midwebapp
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './output'  # Deploy the published output
